### ISSUE TITLE
error "negative branch length found in tree"

### ISSUE THREAD

**Issue by kq1986** [Taming-the-BEAST/FBD-tutorial#8]
Hi Louis,

I am following the FBD tutorial for practice. I used BEAST v.2.7.5 and the .xml files you provided. However, every time there is a similar error: 

...
        1940000     -5521.8582     -5419.0703      -102.7878 15s/Msamples
        1950000     -5533.9924     -5412.6830      -121.3093 15s/Msamples
        1960000     -5541.1663     -5419.5117      -121.6546 15s/Msamples
        1970000     -5560.4289     -5414.4138      -146.0150 15s/Msamples
        1980000     -5523.2824     -5416.1242      -107.1582 15s/Msamples
        1990000     -5510.2942     -5420.2680       -90.0262 15s/Msamples
        2000000     -5504.5693     -5417.7088       -86.8604 15s/Msamples
        2010000     -5524.2829     -5417.8299      -106.4529 15s/Msamples
        2020000     -5528.9979     -5417.2854      -111.7124 15s/Msamples
        2030000     -5514.8036     -5421.9378       -92.8657 15s/Msamples
        2040000     -5524.1484     -5423.1224      -101.0259 15s/Msamples
        2050000     -5532.8400     -5414.0342      -118.8057 15s/Msamples
        2060000     -5528.4930     -5412.6332      -115.8597 15s/Msamples
java.lang.IllegalArgumentException: negative branch length found in tree
	at beastlabs.evolution.tree.RNNIMetric.minHeight(Unknown Source)
	at beastlabs.evolution.tree.RNNIMetric.distance(Unknown Source)
	at beastlabs.evolution.tree.RNNIMetric.distance(Unknown Source)
	at beast.base.evolution.operator.AdaptableOperatorSampler.computeSS(Unknown Source)
	at beast.base.evolution.operator.AdaptableOperatorSampler.accept(Unknown Source)
	at beast.base.inference.MCMC.propagateState(Unknown Source)
	at beast.base.inference.MCMC.doLoop(Unknown Source)
	at beast.base.inference.MCMC.run(Unknown Source)
	at beastfx.app.beast.BeastMCMC.run(Unknown Source)
	at beastfx.app.beast.Controller$2.run(Unknown Source)

I tried with different versions (2.7.x) and platforms (Windows, Linux), but this error still exists. Could you please help me to find out the problem? 

Thanks.
Qi

**Comment by laduplessis** [comment]
Hi Qi, 
There is an error arising from the default operators introduced by the ORC package being incompatible with sampled ancestors trees. We will fix the error soon. 

In the meantime you can solve the issue by using an uncorrelated lognormally distributed relaxed clock model instead (as in older versions of the tutorial). 

Louis

**Comment by kq1986** [comment]
Hi Louis,

Thanks for your reply! I will try with the uncorrelated lognormally distributed relaxed clock model.

Thanks for your help! 

Qi
